name: "Work Report / Bug / Question"
assignees:
  - ImadRedwan
description: "Daily progress reports, Bug reports, Questions for mentor review."
title: "[Report] - "
labels: ["needs-review"]
assignees: []

body:
  - type: dropdown
    id: report_type
    attributes:
      label: "Issue Type"
      description: "Select what type of issue this report represents"
      options:
        - Daily Report
        - Bug / Problem
        - Question / Blocker
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: "Context & Goal"
      description: "What is this issue about? What are you trying to achieve? Why does it matter?"
      placeholder: "Example: Today my goal was to improve the layout of the login form..."
    validations:
      required: true
      minLength: 50

  - type: textarea
    id: details
    attributes:
      label: "Detailed Description"
      description: "Describe what you did or what the problem is — step-by-step. Include what you expected and what actually happened."
      placeholder: "I worked on...\nSteps I took:\n1. ...\n2. ...\nExpected result: ...\nActual result: ..."
    validations:
      required: true
      minLength: 100

  - type: textarea
    id: attachments
    attributes:
      label: "Screenshots / Videos / Code Snippets (Required for UI or Bug Reports)"
      description: "Add visual evidence or code to help understand your issue."
      placeholder: "Upload screenshot or paste snippet here"
    validations:
      required: false

  - type: textarea
    id: technical_notes
    attributes:
      label: "Technical Notes"
      description: "Explain tools, libraries, UI components, structure, constraints, related files…"
      placeholder: "Used React Router...\nRelated files: Router.jsx..."
    validations:
      required: false
      minLength: 50

  - type: textarea
    id: blockers
    attributes:
      label: "Questions & Blockers"
      description: "If you are stuck, explain EXACTLY where and what you need help with."
      placeholder: "I'm stuck because...\nI tried...\nI think the issue might be..."
    validations:
      required: false
      minLength: 30

  - type: textarea
    id: self_assessment
    attributes:
      label: "Self-Assessment"
      description: "What did you learn? What is still unclear? Be honest and reflective."
      placeholder: "Today I learned...\nStill unclear for me..."
    validations:
      required: true
      minLength: 40

  - type: checkboxes
    id: next_steps
    attributes:
      label: "To-Do / Next Steps"
      description: "List the next specific actions you will take."
      options:
        - label: "I have listed at least 2 realistic next steps below"
    validations:
      required: true

  - type: textarea
    id: todo_content
    attributes:
      label: "Next step details"
      placeholder: "- Fix alignment on login button\n- Ask mentor for layout advice"
    validations:
      required: true
      minLength: 20

  - type: input
    id: time_spent
    attributes:
      label: "Time Tracking"
      description: "How many hours did you spend on this?"
      placeholder: "e.g., 4 hours"
    validations:
      required: true
      pattern: "^[0-9]+(\\.[0-9]+)?\\s*(hours?)$"
